# Generated by Django 5.1.15 on 2026-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, help_text='OPIS Truckstop Unique Identifier', unique=True)),
                ('name', models.CharField(help_text='Truckstop Name', max_length=255)),
                ('address', models.CharField(help_text='Street / Highway Exit Address', max_length=255)),
                ('city', models.CharField(db_index=True, help_text='City', max_length=100)),
                ('state', models.CharField(db_index=True, help_text='2-letter US State abbreviation', max_length=2)),
                ('rack_id', models.IntegerField(blank=True, help_text='Rack ID from fuel supplier', null=True)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail diesel price per gallon in USD', max_digits=7)),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='WGS84 Latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='WGS84 Longitude coordinate', null=True)),
                ('geocode_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Status of address geocoding', max_length=20)),
                ('geocode_error', models.TextField(blank=True, default='', help_text='Error message if geocoding failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fuel Station',
                'verbose_name_plural': 'Fuel Stations',
                'ordering': ['state', 'city', 'opis_id'],
                'indexes': [models.Index(fields=['state', 'city'], name='routes_fuel_state_34c75b_idx'), models.Index(fields=['latitude', 'longitude'], name='routes_fuel_latitud_203dad_idx'), models.Index(fields=['geocode_status', 'retail_price'], name='routes_fuel_geocode_11636c_idx')],
            },
        ),
    ]
